# -*- coding: utf-8 -*-
"""cnn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/eya-sassi5/f489f229ef58648ca64526e3d145fd2d/cnn.ipynb
"""

# TP 3 : Réseaux de Neurones Convolutionnels (CNN)
# Ecole Nationale d'Ingénieurs de Sousse (ENISo) - A.U 2025/2026
# Dataset : CIFAR-10

# =============================================================================
# Étape 1 : Importation des bibliothèques
# =============================================================================
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, models
import numpy as np
import matplotlib.pyplot as plt

print("TensorFlow version:", tf.__version__)

# =============================================================================
# Étape 2 : Chargement de la base de données CIFAR-10
# =============================================================================
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data()

# Noms des 10 classes CIFAR-10
class_names = ['avion', 'automobile', 'oiseau', 'chat', 'cerf',
               'chien', 'grenouille', 'cheval', 'bateau', 'camion']

print(f"Forme des données d'entraînement : {x_train.shape}")
print(f"Forme des données de test       : {x_test.shape}")
print(f"Nombre de classes               : {len(class_names)}")

# =============================================================================
# Étape 3 : Visualisation de quelques images
# =============================================================================
plt.figure(figsize=(10, 5))
for i in range(10):
    plt.subplot(2, 5, i + 1)
    plt.imshow(x_train[i])
    plt.title(class_names[y_train[i][0]])
    plt.axis('off')
plt.suptitle("Exemples d'images CIFAR-10", fontsize=14)
plt.tight_layout()
plt.savefig("cifar10_samples.png")
plt.show()
print("Visualisation enregistrée : cifar10_samples.png")

# =============================================================================
# Étape 4 : Normalisation des données
# =============================================================================
# Normalisation des valeurs des pixels entre 0 et 1
x_train = x_train.astype('float32') / 255.0
x_test  = x_test.astype('float32')  / 255.0

print(f"Valeur min après normalisation : {x_train.min()}")
print(f"Valeur max après normalisation : {x_train.max()}")

# =============================================================================
# Étape 5 : Création du modèle Sequential
# =============================================================================
model = models.Sequential([

    # 1. Couche de Convolution : 256 filtres, kernel_size (3,3)
    layers.Conv2D(256, (3, 3), activation='relu',
                  padding='same', input_shape=(32, 32, 3)),

    # 2. Couche de Convolution supplémentaire
    layers.Conv2D(128, (3, 3), activation='relu', padding='same'),

    # 3. Couche de Pooling (MaxPooling)
    layers.MaxPooling2D(pool_size=(2, 2)),

    # 4. Couche de Flatten
    layers.Flatten(),

    # 5a. Couche Fully Connected : 64 nœuds
    layers.Dense(64, activation='relu'),

    # 5b. Couche de sortie : 10 nœuds avec activation sigmoid
    layers.Dense(10, activation='sigmoid')
])

# =============================================================================
# Étape 6 : Compilation du modèle
# =============================================================================
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# =============================================================================
# Étape 7 : Synthèse du modèle
# =============================================================================
model.summary()

# =============================================================================
# Étape 8 : Entraînement du modèle
# =============================================================================
print("\n--- Entraînement du modèle ---")
history = model.fit(
    x_train, y_train,
    epochs=10,
    batch_size=64,
    validation_split=0.1,
    verbose=1
)

# Visualisation des courbes d'entraînement
plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'],    label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Val Accuracy')
plt.title('Précision au cours des époques')
plt.xlabel('Époque')
plt.ylabel('Précision')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'],    label='Train Loss')
plt.plot(history.history['val_loss'], label='Val Loss')
plt.title('Perte au cours des époques')
plt.xlabel('Époque')
plt.ylabel('Perte')
plt.legend()

plt.tight_layout()
plt.savefig("training_curves.png")
plt.show()
print("Courbes d'entraînement enregistrées : training_curves.png")

# =============================================================================
# Étape 9 : Évaluation du modèle
# =============================================================================
print("\n--- Évaluation sur les données de test ---")
test_loss, test_acc = model.evaluate(x_test, y_test, verbose=0)
print(f"Perte sur les données de test    : {test_loss:.4f}")
print(f"Précision sur les données de test: {test_acc:.4f} ({test_acc*100:.2f}%)")

# =============================================================================
# Étape 10 : Amélioration du modèle (avec Dropout + Data Augmentation)
# =============================================================================
print("\n--- Modèle amélioré avec Dropout et Data Augmentation ---")

# Data Augmentation
data_augmentation = keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.1),
    layers.RandomZoom(0.1),
])

model_improved = models.Sequential([

    # Augmentation des données
    data_augmentation,

    # Couche de Convolution 1
    layers.Conv2D(256, (3, 3), activation='relu', padding='same',
                  input_shape=(32, 32, 3)),
    layers.Dropout(0.25),

    # Couche de Convolution 2
    layers.Conv2D(128, (3, 3), activation='relu', padding='same'),

    # Pooling
    layers.MaxPooling2D(pool_size=(2, 2)),
    layers.Dropout(0.25),

    # Flatten
    layers.Flatten(),

    # Fully Connected
    layers.Dense(64, activation='relu'),
    layers.Dropout(0.5),

    # Sortie
    layers.Dense(10, activation='sigmoid')
])

model_improved.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model_improved.summary()

history_improved = model_improved.fit(
    x_train, y_train,
    epochs=10,
    batch_size=64,
    validation_split=0.1,
    verbose=1
)

test_loss_imp, test_acc_imp = model_improved.evaluate(x_test, y_test, verbose=0)
print(f"\n[Modèle amélioré] Perte test    : {test_loss_imp:.4f}")
print(f"[Modèle amélioré] Précision test: {test_acc_imp:.4f} ({test_acc_imp*100:.2f}%)")
print(f"\nAmélioration de la précision    : +{(test_acc_imp - test_acc)*100:.2f}%")